apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: rg-dev-app
  namespace: rg-dev-app
  annotations:
    serviceoperator.azure.com/credential-from: rg-dev-app-aso-credentials
spec:
  location: swedencentral
---
apiVersion: keyvault.azure.com/v1api20210401preview
kind: Vault
metadata:
  name: app-keyvault-31087
  namespace: rg-dev-app
  annotations:
    serviceoperator.azure.com/credential-from: rg-dev-app-aso-credentials
spec:
  location: swedencentral
  owner:
    name: rg-dev-app
    kind: ResourceGroup
  properties:
    tenantId: 4c468b06-7467-4716-b9fa-d3f121c4d307
    sku:
      family: "A"
      name: "standard"
    accessPolicies:
      - tenantId: 4c468b06-7467-4716-b9fa-d3f121c4d307
        objectId: b4b56012-0119-4f07-ad87-5b16b6d42f8a  # User or Service Principal Object ID
        permissions:
          secrets:
            - get
            - list
            - set
    enableSoftDelete: true
